name: habit_tracker
description: Sample habit tarcker app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# consider running `flutter pub upgrade --major-versions`. Alternatively,
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  #default icon pack
  cupertino_icons: ^1.0.2
  #local db
  hive: ^2.1.0
  #state management pkg
  provider: ^6.0.2
  #horizontal calendar
  date_picker_timeline: ^1.2.3
  #weekday selection
  day_picker: ^2.1.1
  #local storage
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  #development lib for the 
  build_runner: ^2.1.7
  #drift databse dev dependency
  drift_dev: ^1.5.2

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
